### ISSUE TITLE
Module TransactSdk requires main queue setup

### ISSUE THREAD

**Issue by robinvk6** [atomicfi/atomic-transact-react-native#12]
We get this warning after adding this library. 
Module TransactSdk requires main queue setup since it overrides `init` but doesn't implement `requiresMainQueueSetup`. In a future release React Native will default to initializing all native modules on a background thread unless explicitly opted-out of.

Can you please provide a newer build with the requiresMainQueueSetup set to true?

**Comment by Tr3yb0** [comment]
Thanks for submitting this. We'll review and respond accordingly as soon as possible.

**Comment by sean-hill** [comment]
@robinvk6 this has been addressed with version 2.6.17. Thanks!
