### ISSUE TITLE
Update kotlin gradle plugin to support rn 0.71

### ISSUE THREAD

**Issue by dnelsonlivecurrence** [atomicfi/atomic-transact-react-native#15]
kotlin gradle plugin is deprecated for rn 0.71

**Comment by sean-hill** [comment]
@dnelsonlivecurrence thanks for reporting this! We're making some React Native updates right now, and will be shipping updates shortly. cc: @contrem @Tr3yb0

**Comment by Tr3yb0** [comment]
@dnelsonlivecurrence thank you so much for reporting this! we're more than happy to review a PR as well, if you'd like to submit one. Otherwise, we'll upgrade the dependency as soon as our RN updates are merged in.

**Comment by dnelsonlivecurrence** [comment]
It looks like the Kotlin version is fairly up to date, so I think I'm just waiting on a new release, thanks.

**Comment by sean-hill** [comment]
@dnelsonlivecurrence we'd published version `2.7.1` :shipit: https://www.npmjs.com/package/@atomicfi/transact-react-native
