### ISSUE TITLE
Animation flickering when opening transact

### ISSUE THREAD

**Issue by giorgiofellipe** [atomicfi/atomic-transact-react-native#28]
We are seeing some flickering on the slide in animation on a few Android devices:
- Xiaomi 14
- Moto G52

The issue seem to not happen on Samsung devices, tested on Samsung A54 and Samsung Note 10+.

https://github.com/user-attachments/assets/2b61a694-9418-4812-9f42-73710dbdf536

**Comment by sean-hill** [comment]
Hi @giorgiofellipe! Thanks for reporting this. We are aware of the issue and are working on a fix. I appreciate your patience, thanks. cc: @contrem

**Comment by contrem** [comment]
fixed in [3.6.3](https://github.com/atomicfi/atomic-transact-react-native/releases/tag/3.6.3)
