### ISSUE TITLE
Value of type 'TransactInteraction' has no member 'data'

### ISSUE THREAD

**Issue by donatoaguirre24** [atomicfi/atomic-transact-react-native#6]
Hi guys, after the last update (1.0.5 -> 1.1.0) we're having issues to build on iOS. Any ideas?

**Environment**
- react-native: 0.67.3
- @atomicfi/transact-react-native: ^1.1.0
- AtomicSDK/AtomicTransact (= 2.2.6)
- iOS deployment target: 14

![image](https://user-images.githubusercontent.com/20030075/156820966-ad71ab58-b49a-4f1f-9510-75d04c6b6a2d.png)
![image](https://user-images.githubusercontent.com/20030075/156821829-dcc80a78-f390-43c3-a29e-41fd43b9e05a.png)
![image](https://user-images.githubusercontent.com/20030075/156821497-54cdfd04-ce23-40e4-92da-fc5732215d12.png)

**Comment by sean-hill** [comment]
This has [been resolved](https://github.com/atomicfi/atomic-transact-react-native/commit/63f0ab6601e98affe2dccf2bd0cc1004c3c0ecdf).
