### ISSUE TITLE
Error: Invalid sdk/platform/version - The version must be a string

### ISSUE THREAD

**Issue by tywayne** [atomicfi/atomic-transact-react-native#7]
[This commit](https://github.com/atomicfi/atomic-transact-react-native/commit/902e07fad13a05b7745ec325ea97c5be04a4a2bf) introduced a bug where you are expecting `Platform.Version` to be a string, but the type of `Platform.Version` provided by `react-native` is actually `string | number`. Because of this, when loaded on Android version 30 (which is a number type), we get this error in the app.

<img width="500" alt="Screen Shot 2022-03-18 at 12 15 55 PM" src="https://user-images.githubusercontent.com/1395543/159052106-e8ae815f-61fc-4486-953b-d90c6a6fb6e0.png">

**Comment by sean-hill** [comment]
@tywayne thanks for reporting this! I'll get it fixed pronto. It was developer error on my part assuming that React Native `Platform.Version` would return the same type for both plaforms.

**Comment by tywayne** [comment]
@sean-hill I had submitted PR #8 already with the fix. You'll likely want to ensure you send in a string on iOS as well, correct?

**Comment by sean-hill** [comment]
I've published version 1.3.0 to this package. Can you give it a try?
